### TensorFlow 설정하기

In [2]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__ )


TensorFlow version: 2.9.1


In [13]:
import cv2
from PIL import Image

### 데이터세트 로드하기
MNIST 데이터세트를 로드하고 준비합니다. 샘플 데이터를 정수에서 부동 소수점 숫자로 변환합니다.

In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()


11490434/11490434 [==============================] - 2s 0us/step


In [17]:
Image.fromarray(x_train[0])

In [18]:
x_train[0]


array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [19]:
x_train, x_test = x_train / 255.0, x_test/ 255.0

In [21]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer = 'adam',
              loss = 'sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [22]:
predictions = model(x_train[:1]).numpy()
predictions

array([[0.06070951, 0.04970889, 0.09458084, 0.10405448, 0.11287229,
        0.20598672, 0.09176881, 0.03719097, 0.14557591, 0.09755161]],
      dtype=float32)

In [23]:
tf.nn.softmax(predictions).numpy()

array([[0.09604193, 0.09499119, 0.09935071, 0.1002964 , 0.1011847 ,
        0.11105905, 0.09907172, 0.09380951, 0.10454851, 0.0996463 ]],
      dtype=float32)

In [24]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [25]:
loss_fn(y_train[:1], predictions).numpy()

2.1976933

In [27]:
model.compile(optimizer='adam', loss=loss_fn, metrics = ['accuracy'])